title = "无心技术簿"
baseURL = "https://www.wuxinvip.com"
languageCode = "en-us"
theme = "ananke"


MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9 # 所有文章 展示列表
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon.ico"
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/huoyan403"
  instagram = ""
  youtube = ""
  github = "https://github.com/wuxinvip"
  linkedin = "http://www.linkedin.com/in/长-连-05215b142/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/slider-bg.jpg"
  recent_posts_number = 3 #首页展示近期文章数目
